# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
#  desc "Generate new localized screenshots"
#  lane :screenshots do
#    capture_screenshots(workspace: "CityList.xcworkspace", scheme: "CityList")
#  end

  desc "Description of what the lane does"
  lane :generate_ipa_develop do
    build_ios_app(
      configuration: "Debug",
      scheme: "CityList",
      clean: true,
      export_method: 'development',
      output_directory: "~/Desktop", # Destination directory. Defaults to current directory.
      output_name: "fastlane_jenkins.ipa",
    )
  end

  lane :clean_xcode do |options|
    clear_derived_data()
    sh("rm -rf ProjectName*zip")
    sh("rm -rf ~/Library/Developer/Xcode/Archives/*")
  end

  lane :code_sign do |options|
    method = "development"
    match(readonly: true, type: method)
  end

  lane :create_build do |options|
    scheme = "CityList"
    configuration = "Development"
    export_method = "development"
    icloud_environment = "Development"
  
    gym(scheme: scheme,
      configuration: configuration,
      export_options:export_options,
      output_name:"ProjectName.ipa")
end
end
